using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Scripts;

namespace Healthie.Tests.Unit;

/// <summary>
/// A <see cref="Container"/> whose every member refuses, so a test double can override the few it
/// actually needs.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="Container"/> is abstract with around forty members, of which this library calls four.
/// Left in the test that uses them, the other thirty-six would bury it. Refusing rather than
/// returning a default is deliberate: a test that reaches a member nobody stubbed has left the path
/// it meant to exercise, and should say so rather than quietly carry on with a null.
/// </para>
/// <para>
/// Hand-written rather than generated by a mocking library, because the repository has no mocking
/// dependency and one type is not a reason to take one.
/// </para>
/// </remarks>
internal abstract class StubContainer : Container
{
    private static NotSupportedException NotStubbed(string member) =>
        new($"{member} is not stubbed. Override it if the test under way is meant to reach it.");

    public override string Id => throw NotStubbed(nameof(Id));

    public override Database Database => throw NotStubbed(nameof(Database));

    public override Conflicts Conflicts => throw NotStubbed(nameof(Conflicts));

    public override Scripts Scripts => throw NotStubbed(nameof(Scripts));

    public override Task<ResponseMessage> CreateItemStreamAsync(Stream streamPayload, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(CreateItemStreamAsync));

    public override TransactionalBatch CreateTransactionalBatch(PartitionKey partitionKey) => throw NotStubbed(nameof(CreateTransactionalBatch));

    public override Task<ContainerResponse> DeleteContainerAsync(ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(DeleteContainerAsync));

    public override Task<ResponseMessage> DeleteContainerStreamAsync(ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(DeleteContainerStreamAsync));

    public override Task<ItemResponse<T>> DeleteItemAsync<T>(string id, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(DeleteItemAsync));

    public override Task<ResponseMessage> DeleteItemStreamAsync(string id, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(DeleteItemStreamAsync));

    public override ChangeFeedEstimator GetChangeFeedEstimator(string processorName, Container leaseContainer) => throw NotStubbed(nameof(GetChangeFeedEstimator));

    public override ChangeFeedProcessorBuilder GetChangeFeedEstimatorBuilder(string processorName, ChangesEstimationHandler estimationDelegate, TimeSpan? estimationPeriod) => throw NotStubbed(nameof(GetChangeFeedEstimatorBuilder));

    public override FeedIterator<T> GetChangeFeedIterator<T>(ChangeFeedStartFrom changeFeedStartFrom, ChangeFeedMode changeFeedMode, ChangeFeedRequestOptions? changeFeedRequestOptions) => throw NotStubbed(nameof(GetChangeFeedIterator));

    public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilder(string processorName, ChangeFeedStreamHandler onChangesDelegate) => throw NotStubbed(nameof(GetChangeFeedProcessorBuilder));

    public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilder<T>(string processorName, ChangeFeedHandler<T> onChangesDelegate) => throw NotStubbed(nameof(GetChangeFeedProcessorBuilder));

    public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilder<T>(string processorName, ChangesHandler<T> onChangesDelegate) => throw NotStubbed(nameof(GetChangeFeedProcessorBuilder));

    public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilderWithManualCheckpoint(string processorName, ChangeFeedStreamHandlerWithManualCheckpoint onChangesDelegate) => throw NotStubbed(nameof(GetChangeFeedProcessorBuilderWithManualCheckpoint));

    public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilderWithManualCheckpoint<T>(string processorName, ChangeFeedHandlerWithManualCheckpoint<T> onChangesDelegate) => throw NotStubbed(nameof(GetChangeFeedProcessorBuilderWithManualCheckpoint));

    public override FeedIterator GetChangeFeedStreamIterator(ChangeFeedStartFrom changeFeedStartFrom, ChangeFeedMode changeFeedMode, ChangeFeedRequestOptions? changeFeedRequestOptions) => throw NotStubbed(nameof(GetChangeFeedStreamIterator));

    public override Task<IReadOnlyList<FeedRange>> GetFeedRangesAsync(CancellationToken cancellationToken) => throw NotStubbed(nameof(GetFeedRangesAsync));

    public override IOrderedQueryable<T> GetItemLinqQueryable<T>(bool allowSynchronousQueryExecution, string? continuationToken, QueryRequestOptions? requestOptions, CosmosLinqSerializerOptions? linqSerializerOptions) => throw NotStubbed(nameof(GetItemLinqQueryable));

    public override FeedIterator<T> GetItemQueryIterator<T>(FeedRange feedRange, QueryDefinition queryDefinition, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryIterator));

    public override FeedIterator<T> GetItemQueryIterator<T>(QueryDefinition queryDefinition, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryIterator));

    public override FeedIterator<T> GetItemQueryIterator<T>(string? queryText, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryIterator));

    public override FeedIterator GetItemQueryStreamIterator(FeedRange feedRange, QueryDefinition queryDefinition, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryStreamIterator));

    public override FeedIterator GetItemQueryStreamIterator(QueryDefinition queryDefinition, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryStreamIterator));

    public override FeedIterator GetItemQueryStreamIterator(string? queryText, string? continuationToken, QueryRequestOptions? requestOptions) => throw NotStubbed(nameof(GetItemQueryStreamIterator));

    public override Task<ItemResponse<T>> PatchItemAsync<T>(string id, PartitionKey partitionKey, IReadOnlyList<PatchOperation> patchOperations, PatchItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(PatchItemAsync));

    public override Task<ResponseMessage> PatchItemStreamAsync(string id, PartitionKey partitionKey, IReadOnlyList<PatchOperation> patchOperations, PatchItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(PatchItemStreamAsync));

    public override Task<ContainerResponse> ReadContainerAsync(ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadContainerAsync));

    public override Task<ResponseMessage> ReadContainerStreamAsync(ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadContainerStreamAsync));

    public override Task<ResponseMessage> ReadItemStreamAsync(string id, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadItemStreamAsync));

    public override Task<FeedResponse<T>> ReadManyItemsAsync<T>(IReadOnlyList<(string id, PartitionKey partitionKey)> items, ReadManyRequestOptions? readManyRequestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadManyItemsAsync));

    public override Task<ResponseMessage> ReadManyItemsStreamAsync(IReadOnlyList<(string id, PartitionKey partitionKey)> items, ReadManyRequestOptions? readManyRequestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadManyItemsStreamAsync));

    public override Task<int?> ReadThroughputAsync(CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadThroughputAsync));

    public override Task<ThroughputResponse> ReadThroughputAsync(RequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReadThroughputAsync));

    public override Task<ContainerResponse> ReplaceContainerAsync(ContainerProperties containerProperties, ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceContainerAsync));

    public override Task<ResponseMessage> ReplaceContainerStreamAsync(ContainerProperties containerProperties, ContainerRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceContainerStreamAsync));

    public override Task<ItemResponse<T>> ReplaceItemAsync<T>(T item, string id, PartitionKey? partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceItemAsync));

    public override Task<ResponseMessage> ReplaceItemStreamAsync(Stream streamPayload, string id, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceItemStreamAsync));

    public override Task<ThroughputResponse> ReplaceThroughputAsync(ThroughputProperties throughputProperties, RequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceThroughputAsync));

    public override Task<ThroughputResponse> ReplaceThroughputAsync(int throughput, RequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(ReplaceThroughputAsync));

    public override Task<ResponseMessage> UpsertItemStreamAsync(Stream streamPayload, PartitionKey partitionKey, ItemRequestOptions? requestOptions, CancellationToken cancellationToken) => throw NotStubbed(nameof(UpsertItemStreamAsync));
}
